name: moorwebworkers
description: A web app that uses AngularDart Components
# version: 0.0.1
# author: marcgraub <marcgraub@gmail.com>

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  dorker:
    git: https://github.com/yuan-kuan/dorker.git
  js: ^0.6.1+1
  moor: #^2.4.2
    path: ./moor/moor
  rxdart: ^0.23.1

dependency_overrides:
  moor_generator:
    path: ./moor/moor_generator
  moor:
    path: ./moor/moor

dev_dependencies:
  build_runner: ^1.8.0
  build_test: ^0.10.10
  build_web_compilers: ^2.9.0
  extra_pedantic: ^1.2.0
  intl_translation: ^0.17.7
  json_serializable: ^3.3.0
  moor_generator: #^2.3.1
    path: ./moor/moor_generator
  pedantic: ^1.9.0
  test: ^1.9.4